### ISSUE TITLE
Congrats! 🎉

### ISSUE THREAD

**Issue by thaoshibe** [Yueming6568/MDMGAN#1]
Congrats on your project! I'd like to add your paper to my [awesome-makeup-transfer](https://github.com/thaoshibe/awesome-makeup-transfer).
Feel free to ping if your paper get accepted to [any] conference!!

**Comment by Yueming6568** [comment]
Thank you very much for your attention ：）
Of course you can add my [MDMGAN](https://arxiv.org/abs/2109.14525) to your [awesome-makeup-transfer](https://github.com/thaoshibe/awesome-makeup-transfer).
I will ping it if my paper is accepted by some conference~
